[project]
name = "oh-my-duck-isaac-asset-tools"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = ["oh-my-duck", "isaacsim[all,extscache]==6.0.1.0"]

[tool.uv.sources]
oh-my-duck = { path = "../..", editable = true }

[tool.uv]
package = false
index-strategy = "unsafe-best-match"
prerelease = "allow"
environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]

[[tool.uv.index]]
url = "https://pypi.nvidia.com"
