from typing import Protocol

from ..contracts.events import EpisodeEvent
from ..tools.catalog import ToolDefinition


class HarnessBridge(Protocol):
    async def register_tools(self, tools: tuple[ToolDefinition, ...]) -> None: ...
    async def submit_text(self, text: str, *, session_id: str, request_id: str) -> None: ...
    async def publish_event(self, event: EpisodeEvent) -> None: ...
    async def submit_experience(self, *, episode_id: str, evidence_refs: tuple[str, ...]) -> None: ...
